## Project-wide Gradle settings.
#
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx10248m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx3g -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.jvmargs=-Xmx3g

# quiet,warn,lifecycle,info,debug  lifeccyle default
org.gradle.logging.level=quiet
# all,none,summary
org.gradle.warning.mode=none

## Performance docs..gradle.org/current/userguide/performance.html
org.gradle.daemon=true
#org.gradle.caching=true
#org.gradle.caching.debug=true
#org.gradle.logging.level=debug
#org.gradle.logging.stacktrace=full
#logging.level=LogLevel.DEBUG

android.useAndroidX=true
android.nonFinalResIds=false
android.nonTransitiveRClass=false
android.enableBuildScriptClasspathCheck=false

# Moved into app build.gradle
# android.defaults.buildfeatures.buildconfig=true
